### ISSUE TITLE
better git settings

### ISSUE THREAD

**Issue by vangeest** [emmauscollege/4HV-game-template#9]
Suggestie voor betere git-settings. Beter is: eenvoudiger voor leerlingen.
Ik heb het alleen zelf getest, niet met leerlingen. Misschien dat jij nog andere ideeen hebt.

Als je dit wilt implementeren:
zet navolgende inhoud in
.vscode/settings.json

{
    "git.useEditorAsCommitInput": false, // prevent editor looking like continouosly busy after committing with an empty message
    "git.confirmSync": false, // disable pop-up with confirmation questions after click on synchronise
    "git.enableSmartCommit": true, // stage all changes when none of the changes are stages, instead of showing pop-up with a warning
    "git.rebaseWhenSync": true, // leads to easier flow for students in case of conflicting commits
    "git.postCommitCommand": "sync", // sync automatically after each commit
    "git.mergeEditor": true, // open merge-editor for files under conflict
	"git.autofetch": true, // autofetch (fetch means count, not read) changes from github periodically
    "git.autofetchPeriod": 60 // autofetch period 60 seconds
}

**Comment by cam-emmauscollege** [comment]
@vangeest: ik twijfel alleen over git.rebaseWhenSync": true

We zouden dat eens samen even moeten uitproberen.

**Comment by vangeest** [comment]
Okee, alle regels behalve git.rebaseWhenSync": true heb ik alvast gecommit.

Ik twijfel ook over rebase of merge.
Ik heb hier gekeken:
https://www.edureka.co/blog/git-rebase-vs-merge/
en ik kreeg de indruk dat rebase wat eenvoudiger was te begrijpen.

**Comment by vangeest** [comment]
geimplementeerd met merge (rebase regel uitgecommentarieerd)
